### ISSUE TITLE
Power on/off the unit via php/raspi

### ISSUE THREAD

**Issue by fcattaneo2** [ael-code/daikin-control#15]
Hi all.
I'm installed this web gui and use it for manage my Daikin FTXM unit.

Now I'm trying to switch on/off the unit via http but I do not understand how I do it .
( my idea is use curl or sometings like this, for auto-manage the unit )

i try this via browser without success : 
http://192.168.1.91/aircon/set_control_info?pow=1

Is there a way to turn on the unit without sending all the parameters?

There is an example to use your api ( api.php ) without  gui ?  

Thanks,
Fabrizio.

**Comment by ael-code** [comment]
> Hi all.
> I'm installed this web gui and use it for manage my Daikin FTXM unit.
> 

Nice to hear someone is using it :)

> Now I'm trying to switch on/off the unit via http but I do not understand how I do it .
> ( my idea is use curl or sometings like this, for auto-manage the unit )
> 
> i try this via browser without success :
> http://192.168.1.91/aircon/set_control_info?pow=1
> 
> Is there a way to turn on the unit without sending all the parameters?
>

Unfortunately the answer is NO. Some parameters are mandatory. The documentation wasn't so clear on this point, so I've updated it. You can try to have a look at the [improved section](https://github.com/ael-code/daikin-control#minimal-parameters-set).

You can use pretty any http client for making the request, I usually use curl to make some tests.

> There is an example to use your api ( api.php ) without gui ?
> 

I wrote this code long time ago... If you want to interact with the air conditioner, my suggestion is to use an http client or a intermediate library. I've added to the README a section with links to external libraries.

Some time ago I wrote a python library https://github.com/ael-code/daikin-aricon-pylib that can be used to build more complex stuff like web gui, script, cli etc.. It should works and provides a very simple API. It's also very nice to use it from the python interactive shell. The only problem is the lack of documentation.

> Thanks,
> Fabrizio.
