### ISSUE TITLE
Tiny slip of the key in README.md

### ISSUE THREAD

**Issue by elfmimi** [ael-code/daikin-control#18]
Here, it should be /**aircon**/set_control_info.  Not /**common**/set_control_info.
https://github.com/ael-code/daikin-control/blame/f4586b947151c4de9b26e4a73480da0f6247d1ab/README.md#L70
https://github.com/ael-code/daikin-control/blame/f4586b947151c4de9b26e4a73480da0f6247d1ab/README.md#L154

**Comment by ael-code** [comment]
Can someone confirm this?

**Comment by Apollon77** [comment]
yes it's correct. in main table it is correct, only the headline is wrong ...
