### ISSUE TITLE
http://daikinsmartdbt.jp/

### ISSUE THREAD

**Issue by quinaz** [ael-code/daikin-control#3]
Hi,
Congratulations for this great initiative with a great potential!
What user/pass shall i use to access this page?!
Thank you.

**Comment by ael-code** [comment]
> Hi,
> Congratulations for this great initiative with a great potential!
> What user/pass shall i use to access this page?!
> Thank you.

Some time ago login was not required. I've dumped the page source code and you can find it [here](https://github.com/ael-code/daikin-control/blob/master/daikinsmartdbt.htm).

If you look page, you'll find a registration api: `/common/add_account`.
I used that page only as api documentation.
