### ISSUE TITLE
Error: control ajax request failed

### ISSUE THREAD

**Issue by quinaz** [ael-code/daikin-control#4]
Hi again,
I'm trying to use web gu i (by opening up.html), and I get this error! Can you pls help?
I've already placed unit IP address in config.php... Am I missing some Things?
Do you have any step by step guide to use it?
Do you know how the iOS app searches for devices in the network?
Thank you again
Manuel

**Comment by ael-code** [comment]
On 06/11/2015 12:31 AM, quinaz wrote:
> Hi again,
> I'm trying to use web gu i (by opening up.html), and I get this error!
> Can you pls help?
> I've already placed unit IP address in config.php... Am I missing some
> Things?

Php files need to be served from a webserver located on the same lan of
the conditioner unit.

> Do you have any step by step guide to use it?

Unfortunately I did not wrote any installation guide. As soon as I'll
have some free time I'll write some documentation.

> Do you know how the iOS app searches for devices in the network?

If I remember well, sniffing pockets I found out that it's something
about broadcast request on the lan.
Indeed the application need some time to find devices.

> Thank you again
> Manuel
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ael-code/daikin-control/issues/4>.
> 

-- 
tommy.ael
gpg key: 0xEBD8B3682C4C4645

**Comment by quinaz** [comment]
"Php files need to be served from a webserver located on the same lan of
the conditioner unit"
How do I do it?!

**Comment by ael-code** [comment]
On 06/11/2015 05:47 PM, quinaz wrote:
> "Php files need to be served from a webserver located on the same lan of
> the conditioner unit"
> How do I do it?!

You need to install a web server and enable php processing. The
installation steps depends on the underling operative system.

**Comment by quinaz** [comment]
Thank you so much for your support!
I put it on my home web server, and I got it to work... suddenly I started to get: "Error: sensor ajax request failed"
Any suggestion of what happened?!

**Comment by nununo** [comment]
Hi,
Thanks for the tool! I just installed it today and it works great.

Interestingly though, I have 3 Daikin units at home. 2 of them worked just fine. But for the third one I get the same error quinaz gets: "Error: sensor ajax request failed".

Each room has its own instance of your tool, each in its own folder. The content of the 3 folders is exactly the same except for the IP address in config.php. I'm quite sure that I have configured the IP address correctly for the third room and if I ping that address it's alive, but somehow it just doesn't work. Any idea why this is happening?

Thanks!
Nuno

**Comment by quinaz** [comment]
The tool is really great... I don't know what happen, but I put it in my home web server with php enabled. I managed to make it work on all 4 machines, but now I'm getting the control and sensor ajax error! I don't understand because it was working!!!
Nuno, se conseguir descobrir o que se passa, avise! Abraço e obrigado.
Sorry ael, but it seems that Nuno is Portuguese like me!!!

**Comment by ael-code** [comment]
> Interestingly though, I have 3 Daikin units at home. 2 of them worked just fine. But for the third one I get the same error quinaz gets: "Error: sensor ajax request failed".

Ajax request could fail for a lot of reason. Can you provide more details? Anyway l'll try to investigate.

**Comment by quinaz** [comment]
None of my 4 units work now!!! Very strange. You can access it at quinaz.pt/daikin/1, 2, 3 and 4, and try it yourself (renamed ui to index).
Thanks

**Comment by ael-code** [comment]
> None of my 4 units work now!!! Very strange. You can access it at quinaz.pt/daikin/1, 2, 3 and 4, and try it yourself (renamed ui to index).
> Thanks

The ajax request failed because receives an http `500` status code. Seems to be a php related error. You should look in your server for php logs.

**Comment by quinaz** [comment]
[Fri Jun 12 10:28:01.404410 2015] [:error] [pid 46081] [client 213.205.85.161:52797] PHP Parse error:  parse error, expecting `"variable (T_VARIABLE)"' or `"${ (T_DOLLAR_OPEN_CURLY_BRACES)"' or `"{$ (T_CURLY_OPEN)"' in /Library/Server/Web/Data/Sites/quinazpt/daikin/1/config.php on line 7, referer: http://quinaz.pt/daikin/1/
[Fri Jun 12 10:28:01.419902 2015] [:error] [pid 46076] [client 213.205.85.161:52798] PHP Parse error:  parse error, expecting `"variable (T_VARIABLE)"' or `"${ (T_DOLLAR_OPEN_CURLY_BRACES)"' or `"{$ (T_CURLY_OPEN)"' in /Library/Server/Web/Data/Sites/quinazpt/daikin/1/config.php on line 7, referer: http://quinaz.pt/daikin/1/

**Comment by ael-code** [comment]
can you post your `/Library/Server/Web/Data/Sites/quinazpt/daikin/1/config.php`

**Comment by quinaz** [comment]
<?php
	//ip of the airconditioner
	
	$ip="192.168.1.10”;

?>

**Comment by ael-code** [comment]
> <?php
> //ip of the airconditioner
> 
> $ip="192.168.1.10”;
> 
> ?>

seems that you use two different kind of apices to enclose the ip.

**Comment by nununo** [comment]
Olá quinaz :)

I'll let you know if I find a solution. Let us know also.
Regards,
Nuno

**Comment by quinaz** [comment]
Solved!!! I just downloaded the file again and the config.php seems to have the closing apices of the IP different from the first one... the original file! I simply copy/paste the opening apices on the closing apices and voila...
2 suggestions... allow to control more than 1 unit in the same screen... a login and pass would be welcome, otherwise anyone from the net can access it!!!
Nuno, copiei as primeiras aspas em cima das segundas... não sei porquê, mas eram diferentes!!!
Thanks a lot AEL

**Comment by nununo** [comment]
That was it! I also soved it by replacing the fancy " with a normal one.

I know how this happened. I used TextEdit instead of XCode on this
particular one.

Great! Thanks!
