### ISSUE TITLE
err=255

### ISSUE THREAD

**Issue by Pyr0x3n** [ael-code/daikin-control#8]
Thanks för this app!
A question. I have 5 units 3 work well but 2 of my units does not respond to the commands an throw error err=255

http://192.168.0.84/common/basic_info
ret=OK,type=aircon,reg=eu,dst=1,ver=2_2_5,pow=0,err=255,location=0,name=%56%61%72%64%61%67%73%72%75%6d,icon=0,method=polling,port=30050,id=XXXX,pw=XXXXX,lpw_flag=0,adp_kind=2,pv=2,cpv=2,led=0,en_setzone=1,mac=XXXXXXXX,adp_mode=run

Anu idea what is the err=255

**Comment by Pyr0x3n** [comment]
I've discovered a new undocumented command
/common/reboot
This rebooted the AP and solved my problems

**Comment by ael-code** [comment]
> I've discovered a new undocumented command
> `/common/reboot`
> This rebooted the AP and solved my problems

Do you want to contribute and insert it in the docs?

**Comment by Pyr0x3n** [comment]
response "ret=OK", I guessed on the command, guessing that some general commands should be under /common/...

**Comment by ael-code** [comment]
Good contribution! Thanks
